-- local status_ok, dap = pcall(require, "dap")
-- if not status_ok then
--   return
-- end
--
-- local status_ruby_dap_ok, dapruby = pcall(require, "dap-ruby")
-- if not status_ruby_dap_ok then
--   return
-- end
--
--
-- dapruby.setup()
require('dap-ruby').setup()

-- local dap = require('dap')
-- dap.adapters.ruby = {
--   type = 'executable';
--   command = 'bundle';
--   args = {'exec', 'readapt', 'stdio'};
-- }
--
-- dap.configurations.ruby = {
--   {
--     type = 'ruby';
--     request = 'launch';
--     name = 'Rails';
--     program = 'bundle';
--     programArgs = {'exec', 'rails', 's'};
--     useBundler = true;
--   },
-- }
