os:
  editPreset: "nvim-remote"
  edit: "nvr --nostart --remote-silent -l {{filename}}"
gui:
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - "#848b98"
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
    optionsTextColor:
      - magenta
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
  commitLength:
    show: true
git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  commit:
    signOff: false
  merging:
    manualCommit: false
    args: ""
  log:
    showWholeGraph: false
  autoFetch: true
  autoRefresh: true
  overrideGpg: false
  disableForcePushing: false
  parseEmoji: false
  diffContextSize: 3
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium
keybinding:
  universal:
    prevItem: "k"
    nextItem: "j"
  commits:
    moveDownCommit: J
    moveUpCommit: K
