---
include:
- Rakefile
- Gemfile
- "*.gemspec"
- "**/*.rb"
exclude:
- views/**/*
- bundle/**/*
- node_modules/**/*
- spec/**/*
- test/**/*
- vendor/**/*
require: []
domains: []
reporters:
- standardrb
- reek
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
# plugins:
# - solargraph-rails
# - solargraph-standardrb
# - solargraph-reek
max_files: 5000
