# frozen_string_literal: true

source 'http://rubygems.org'
gem 'debase'
gem 'interactive_editor'
gem 'reek'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubocop-rails'
gem 'rubocop-rspec'
gem 'ruby-debug-ide'
gem 'rufo'
gem 'solargraph'
