source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

gem "erb_lint", "0.3.1"
gem "erb-formatter"
gem "solargraph", "0.48"
gem "solargraph-rails"
gem "solargraph-standardrb"
gem "standard"
gem "solargraph-reek"
gem "yard"
gem "json"
gem "rubocop", "1.48.1"
