source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

gem "erb_lint"
gem "erb-formatter", git: "https://github.com/nebulab/erb-formatter", branch: "main"
gem "solargraph", "0.50"
gem "solargraph-rails"
gem "solargraph-standardrb"
gem "standard"
gem "solargraph-reek"
gem "yard"
gem "json"
gem "rubocop", "1.48.1"
gem "ruby-lsp"
